name: pynoticenter
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.9.13
  - black=22.6.0
  - sphinx=5.1.1
  - pip:
    - asyncio==3.4.3
    - myst_parser==0.18.0
    - recommonmark==0.7.1
    - sphinx-intl==2.0.1
